spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/HELIPAY_DEV
    username: HELIPAY_USER
    password: HELIPAY_PASS
    driver-class-name: org.postgresql.Driver